#!/usr/local/bin/python2.5


def pl_up():
	global playlistpos
	playlistpos=playlistpos-1
	if playlistpos<0:
	    playlistpos=0
def pl_down():
	global playlistpos
	playlistpos=playlistpos+1
def pl_pgup():
	global playlistpos
	playlistpos=playlistpos-20
	if playlistpos<0:
	    playlistpos=0
def pl_pgdown():
	global playlistpos
	playlistpos=playlistpos+20
def pl_end():
	global playlistpos
	global playlist
	playlistpos=len(playlist)-1
def pl_home():
	global playlistpos
	global playlist
	playlistpos=0

def pl_ay():
	global playlistpos
	global playlist
	
#	xyzzy.play(playlist[playlistpos])
	xyzzy.play(playlist[wannaplay])
	

def wanna_play():
	global playlistpos
	global wannaplay
	wannaplay=playlistpos

def dr_aw():
	global playlistpos
	global playlist
	y=0
	b=0
	for i in playlist:
	    if abs(playlistpos-b)>10:
		pass
	    else:
		sel=0
		if b == playlistpos:
		    xyzzy.adjs(y)
		    sel=1
    		    xyzzy.printline(-60,y,"*",1)
		xyzzy.printline(0,y,i,0)
		if b == playlistpos:
		    pass
	    y=y+60
	    b=b+1
	    
def getplaylistpos():
	global playlistpos
	return playlistpos

f=open("pl","r")
playlist=f.readlines()
playlistpos=0;
